---
title: "Pico Seedlings"
author: "Anna Talucci"
date: "November 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
# Packages

The following Packages are required for the below analyses:

```{r message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
```

# Data

```{r}
data = read.csv("../data/SeedlingCts_FireSeverity.csv", header = TRUE, sep = ",", strip.white = TRUE)
head(data)
```
```{r}
data$seedling.area
```

```{r}
subplot = data %>% filter(seedling.area == 4) %>%
  mutate(seed_ct_100 = round(seedling.ct * 25)) %>%
  mutate(area = 100)
```

```{r}
quad1 = data %>% filter(seedling.area == 52) %>%
  mutate(seed_ct_100 = round(seedling.ct * 1.92)) %>%
  mutate(area = 100)
```

```{r}
quad2 = data %>% filter(seedling.area == 51) %>%
  mutate(seed_ct_100 = round(seedling.ct * 1.96)) %>%
  mutate(area = 100)
```

```{r}
plot = data %>% filter(seedling.area == 100) %>%
  mutate(seed_ct_100 = (seedling.ct)) %>%
  mutate(area = 100)
```

```{r}
data2 = rbind(subplot, quad1, quad2, plot)
```

```{r}
summary(data2)
```


```{r}
bquote('x axis'~(Å^2))
```

```{r fig.height=5, fig.width=6}
plot1 = ggplot(data=data2, aes(x=seed_ct_100, fill = fire.type)) +
    geom_density(alpha=0.5) +
  scale_fill_manual(values = c("#f03b20", "#feb24c", "#fdfd96", "#0B6623"), name="Fire Severity",
                         breaks=c("crown", "sev.surf", "surface", "unburned"),
                         labels=c("Crown", "Severe Surface", "Light Surface", "Unburned")) +
  labs(x=bquote("Seedling counts per 100" ~m^2), y = "Density") +
    theme_bw() +
  theme(legend.position = "bottom")

plot1
```

```{r}
ggsave("../figures/SeedlingCounts.png", plot = plot1, width = 6, height = 5, units = "in", dpi = 300)
```

